import type { Metadata, Viewport } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import "./globals.css"

import { ThemeWrapper } from "@/wrappers/ThemeWrapper"

import { Footer } from "@/components/server/footer"

import { cn } from "@/lib/utils"
import { Navigation } from "@/components/server/navigation"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"]
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
}

export const viewport: Viewport = {
  initialScale: 1,
  width: "device-width"
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          geistSans.variable,
          geistMono.variable,
          "dark:bg-background text-foreground flex min-h-screen flex-col bg-pink-100 font-sans antialiased"
        )}
      >
        <ThemeWrapper>
          <Navigation />
          <main className="grow px-4 pt-36 sm:px-8">{children}</main>
          <Footer />
        </ThemeWrapper>
      </body>
    </html>
  )
}
